### ISSUE TITLE
Additional coverage measurements

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#411]
Tracking/reference issue for additional coverage measurements that 
+ can be added in `0.7.0`
+ we have a plausible way of implementing
--------

- [ ] Public storage variable line coverage (#281) ([design idea](https://github.com/sc-forks/solidity-coverage/issues/281#issue-355931089))
- [ ] Modifier-hits-at-call-site branch coverage (#286) ([design idea](https://github.com/sc-forks/solidity-coverage/issues/286#issuecomment-511580253)
- [ ] && / || Coberatura-style branch coverage (#175) ([design idea](https://github.com/sc-forks/solidity-coverage/issues/175#issuecomment-532020343))
- [ ] Restore ternary conditional branch coverage (#219) ([design idea](https://github.com/sc-forks/solidity-coverage/issues/219#issuecomment-533739499)) 
- [ ] Documentation coverage (investigate viability at solidity-parser-antlr)
