### ISSUE TITLE
Prerequisites for publishing solidity-coverage 0.8.0

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#701]
(This list actively edited)

**TODO**
- [x] rebase #502 against master
  + (a little challenging)
- [x] investigate and fix #700
- [x] restructure repo to publish truffle-solidity-coverage and solidity-coverage separately
  - [x] remove truffle-provider from solidity-coverage dependencies
  - [ ] fix #694 (ganache)

**Comment by barakman** [comment]
Hi. Is there an ETA on this?

**Comment by mejango** [comment]
also curious. thanks, this project has been a massive sanity check as we get ready to deploy.

**Comment by cgewecke** [comment]
I should have some time for this later this week...

**Comment by Nipol** [comment]
What do you think about viaIR support? In my case, the test case will pass, but the coverage will be 0%.

**Comment by mejango** [comment]
updates @cgewecke?
If there's a good chance its not gonna happen, all good, just might as well se the expectation. <3

**Comment by cgewecke** [comment]
It's going to happen, I'm just running behind sorry.

**Comment by cgewecke** [comment]
@mejango The beta version is patched and #700 should be resolved for the moment.

**Comment by parv3213** [comment]
Hey team! When can we expect support for `viaIR`? 
Meanwhile, is there any workaround to support this locally?

**Comment by cgewecke** [comment]
@parv3213 There are some tricks to configuring the optimizer if you're hitting `stack too deep` without `viaIR` at the link below. (viaIR has to be turned off because it strips out solidity-coverage's instrumentation - see #715)

https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#running-out-of-stack

**Comment by barakman** [comment]
Working, thank you!
