### ISSUE TITLE
v0.9.0 Road Map 

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#825]
**TO DO**

- [ ] Upgrade / redo test suite for solidity 0.8.x and hardhat client
- [ ] Investigate [slang][2] and use parser if possible
- [ ] Fix `viaIR` problems (#715) by instrumenting with yul [verbatim][1] function where possible
  + exclude file-level stuff
- [ ] Migrate to nyc
  + add docs recipe for combining foundry and solidity-coverage reports
- [ ] fix remaining instrumentation errors
  + #821 (ternary operator after else without parens)
  + #751 (multiple ternary operators in one expression)
- [ ] Normalize behavior of `skipFiles` option
  + Add command to specify files to cover
- [ ] Investigate instrumentation perf improvements
  + parallel (?)
  + lazy comp (?)
- [ ] Figure out what to do about EDR...
- [ ] Add recipes section to docs (after trawling issues)
- [ ] Update API docs section

[1]: https://docs.soliditylang.org/en/v0.8.23/yul.html#verbatim
[2]: https://github.com/NomicFoundation/slang
